version: 2
updates:
- package-ecosystem: elm
  directory: "/frontend/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  versioning-strategy: lockfile-only
