version: '3.7'
services:
  web:
    build:
      context: .
    command: thin start
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/var/app
    environment:
      DOCKER: 'true'
  elm:
    build:
      context: .
    command: rake elm:watch
    stdin_open: true
    tty: true
    volumes:
      - .:/var/app
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    environment:
      PORTS: 5000
